2023-08-12 16:06:20,215 - worker_process - INFO - Worker_process started.
2023-08-12 16:06:20,233 - HEModelEncryptor - INFO - Using HE model encryptor.
2023-08-12 16:06:20,233 - HEModelEncryptor - INFO - client weights control: {}
2023-08-12 16:06:20,233 - HEModelEncryptor - INFO - Encrypting all layers
2023-08-12 16:06:20,233 - HEModelEncryptor - INFO - Using HE model encryptor.
2023-08-12 16:06:20,233 - HEModelEncryptor - INFO - client weights control: {}
2023-08-12 16:06:20,234 - HEModelEncryptor - INFO - Encrypting all layers
2023-08-12 16:06:20,234 - HEModelDecryptor - INFO - Using HE model decryptor.
2023-08-12 16:06:20,234 - JsonScanner - ERROR - Traceback (most recent call last):
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 98, in _do_scan
    node.processor.process_element(node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 135, in process_element
    self.process_config_element(self.config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 74, in process_config_element
    FedJsonConfigurator.process_config_element(self, config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed_json_config.py", line 75, in process_config_element
    c = self.authorize_and_build_component(element, config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 106, in authorize_and_build_component
    t = super().authorize_and_build_component(config_dict, config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 104, in authorize_and_build_component
    return self.build_component(config_dict)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/component_builder.py", line 86, in build_component
    return instantiate_class(class_path, class_args)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 51, in instantiate_class
    c = get_class(class_path)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 30, in get_class
    module_ = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pt'

2023-08-12 16:06:20,235 - worker_process - ERROR - FL client execution exception: ConfigError: Error processing ['/home/deto/Desktop/Projects/cifar10_v1/cifar10-real-world/workspaces/secure_workspace/site-5/startup/../4d034f78-e530-45c6-b318-1d3f2f293fdf/app_site-5/config/config_fed_client.json'] in JSON element {'id': 'cifar10-learner', 'path': 'pt.learners.cifar10_learner.CIFAR10Learner', 'args': {'train_idx_root': '/tmp/cifar10_splits/cifar10_fedavg_he_alpha1.0_8d7cbf33-e4a5-4ae9-9235-cdaace4f85bc', 'aggregation_epochs': 4, 'lr': 0.01}}: path: components.#1, exception: ModuleNotFoundError: No module named 'pt'
2023-08-12 16:06:20,235 - FederatedClient - INFO - Shutting down client run: site-5
2023-08-12 16:06:21,218 - MPM - ERROR - Traceback (most recent call last):
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 98, in _do_scan
    node.processor.process_element(node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 135, in process_element
    self.process_config_element(self.config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 74, in process_config_element
    FedJsonConfigurator.process_config_element(self, config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed_json_config.py", line 75, in process_config_element
    c = self.authorize_and_build_component(element, config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 106, in authorize_and_build_component
    t = super().authorize_and_build_component(config_dict, config_ctx, node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 104, in authorize_and_build_component
    return self.build_component(config_dict)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/component_builder.py", line 86, in build_component
    return instantiate_class(class_path, class_args)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 51, in instantiate_class
    c = get_class(class_path)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 30, in get_class
    module_ = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/f3/mpm.py", line 146, in run
    rc = main_func()
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/app/client/worker_process.py", line 140, in main
    raise e
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/app/client/worker_process.py", line 136, in main
    client_app_runner.start_run(app_root, args, config_folder, federated_client, secure_train, sp, conf.handlers)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/client/client_app_runner.py", line 43, in start_run
    self.client_runner = self.create_client_runner(
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/fed/client/client_app_runner.py", line 80, in create_client_runner
    conf.configure()
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 132, in configure
    raise e
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 129, in configure
    self._do_configure()
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 122, in _do_configure
    self.json_scanner.scan(self)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 164, in scan
    self._do_scan(node)
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 137, in _do_scan
    self._do_scan(_child_node(node, k, 0, v))
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 140, in _do_scan
    self._do_scan(_child_node(node, node.key, i + 1, element[i]))
  File "/home/deto/Desktop/Projects/environments/nvflare-venv/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 119, in _do_scan
    raise ConfigError(
nvflare.fuel.common.excepts.ConfigError: Error processing ['/home/deto/Desktop/Projects/cifar10_v1/cifar10-real-world/workspaces/secure_workspace/site-5/startup/../4d034f78-e530-45c6-b318-1d3f2f293fdf/app_site-5/config/config_fed_client.json'] in JSON element {'id': 'cifar10-learner', 'path': 'pt.learners.cifar10_learner.CIFAR10Learner', 'args': {'train_idx_root': '/tmp/cifar10_splits/cifar10_fedavg_he_alpha1.0_8d7cbf33-e4a5-4ae9-9235-cdaace4f85bc', 'aggregation_epochs': 4, 'lr': 0.01}}: path: components.#1, exception: ModuleNotFoundError: No module named 'pt'

2023-08-12 16:06:21,219 - MPM - INFO - MPM: Good Bye!
